version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: test-bot-app
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/welcome"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
