name: Docker Build and Push

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and test
      run: |
        docker build -t test-bot-app .
        docker run --name test-container -d -p 8000:8000 test-bot-app
        sleep 5
        curl http://localhost:8000/api/welcome
        docker stop test-container
        docker rm test-container
        
    # The following steps would be used in a real-world scenario to push to a registry
    # Uncomment and configure as needed
    
    # - name: Login to DockerHub
    #   if: github.event_name != 'pull_request'
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # - name: Extract metadata for Docker
    #   id: meta
    #   uses: docker/metadata-action@v3
    #   with:
    #     images: your-dockerhub-username/test-bot-app
    #     tags: |
    #       type=ref,event=branch
    #       type=ref,event=pr
    #       type=semver,pattern={{version}}
    
    # - name: Build and push
    #   if: github.event_name != 'pull_request'
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     push: true
    #     tags: ${{ steps.meta.outputs.tags }}
    #     labels: ${{ steps.meta.outputs.labels }}
